### ISSUE TITLE
color 808080 is not recognized as color

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc-ui#66]
https://docs.2sxc.org/basics/browser/edit-ux/toolbars/customize.html#special-notes

- [x] color=gray
- [x] color=80807F
- [ ] color=808080

If the color contains only numbers, it is not recognized as the color for a button.

Example 
```
["toolbar=empty?contentType=Person&entityId=756",
 "edit",
 "delete&color=808080?entityGuid=c5a71c04-9b41-465c-8cdf-724052cdfa6d&title=Anna-Marie"]
```
=> 
![image](https://user-images.githubusercontent.com/5693190/110941369-8eac5d00-8338-11eb-9867-4293c78652a0.png)

**Comment by iJungleboy** [comment]
In this case you must use the hash so `#808080` should work 😉

**Comment by SCullman** [comment]
![image](https://user-images.githubusercontent.com/5693190/110955603-0e8ef300-834a-11eb-8164-2cd6aa53bf5b.png)

Even the specs say I must not use the hash.

**Comment by iJungleboy** [comment]
Ok, we'll check.

**Comment by iJungleboy** [comment]
Thx for posting this. A a temporary workaround just use a slightly lower number like 7F7F7F

**Comment by iJungleboy** [comment]
Was a JS issue - 808080 was regarded as number instead of string, will be fixed in next release. thx for reporting.
